name: Renovate
on:
  schedule:
    - cron: '0/15 * * * *'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Get Yarn cache directory
        run: echo "::set-output name=YARN_CACHE_DIR::$(yarn config get cacheFolder)"
        id: yarn-cache-dir
      - name: Get Yarn version
        run: echo "::set-output name=YARN_VERSION::$(yarn --version)"
        id: yarn-version
      - name: Cache yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.YARN_CACHE_DIR }}
          key: yarn-cache-${{ runner.os }}-${{ steps.yarn-version.outputs.YARN_VERSION }}-${{ hashFiles('yarn.lock') }}
      - run: yarn --immutable
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@7669f209b1c4c8fd9a6179f65d51cccffcd6a891
        with:
          configurationFile: renovate.json5
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
